apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: kube-system
spec:
  certificates:
    - secretName: maxid-me-tls-prod
  defaultCertificate:
    secretName: maxid-me-tls-prod
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-007337-xyz-tls-prod
  namespace: kube-system
spec:
  secretName: maxid-me-tls-prod
  dnsNames:
    - "maxid-me"
    - "*.maxid-me"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
