apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik-v2
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: traefik
    helm:
      parameters:
        - name: installCRDs
          value: "true"
    repoURL: https://traefik.github.io/charts
    targetRevision: v30.1.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true